directories:
  output: release
  buildResources: build
appId: com.binance.demo
productName: BinanceTradingApp
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*.cjs
      - '!dist-electron/**/*.js'
      - node_modules/**/*
      - package.json
extraResources:
  - from: logs
    to: logs
    filter:
      - '**/*'
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: build/icon.ico
mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
  icon: build/icon.icns
  category: public.app-category.finance
linux:
  target:
    - target: AppImage
      arch:
        - x64
  icon: build/icon.png
  category: Finance
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
publish:
  - provider: github
    owner: your-github-username
    repo: your-repo-name
extraMetadata:
  main: dist-electron/main.cjs
electronVersion: 22.3.27
