name: 自动构建和发布

on:
  push:
    tags:
      - 'v*'  # 当推送v开头的标签时触发（如v1.0.0）

jobs:
  build-and-release:
    runs-on: windows-latest  # 使用Windows环境构建Windows安装包

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 构建应用
        run: npm run dist:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 用于发布的GitHub Token

      - name: 发布到GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/*.msi
            dist/*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
